"""Exhaustive scientific exercise catalog and metric calculation definitions."""

from typing import Dict, Any, List

EXERCISE_CATALOG: Dict[str, Dict[str, Any]] = {
    # --- DISTANCE-BASED EXERCISES ---
    "running_outdoor": {
        "id": "running_outdoor",
        "name": "Outdoor Running",
        "category": "distance",
        "met": 8.0,
        "calories_per_km_per_kg": 1.03,  # Scientific running energy cost factor (~1.03 kcal/kg/km)
        "avg_speed_kmh": 10.0,           # ~6 min/km pace
        "unit": "km",
    },
    "running_treadmill": {
        "id": "running_treadmill",
        "name": "Treadmill Running",
        "category": "distance",
        "met": 7.5,
        "calories_per_km_per_kg": 0.98,
        "avg_speed_kmh": 9.5,
        "unit": "km",
    },
    "cycling_outdoor": {
        "id": "cycling_outdoor",
        "name": "Outdoor Cycling",
        "category": "distance",
        "met": 7.5,
        "calories_per_km_per_kg": 0.35,  # ~0.35 kcal/kg/km for moderate cycling
        "avg_speed_kmh": 20.0,
        "unit": "km",
    },
    "cycling_stationary": {
        "id": "cycling_stationary",
        "name": "Stationary Bike",
        "category": "distance",
        "met": 6.8,
        "calories_per_km_per_kg": 0.32,
        "avg_speed_kmh": 18.0,
        "unit": "km",
    },
    "walking_normal": {
        "id": "walking_normal",
        "name": "Normal Walking",
        "category": "distance",
        "met": 3.5,
        "calories_per_km_per_kg": 0.65,
        "avg_speed_kmh": 4.5,
        "unit": "km",
    },
    "walking_brisk": {
        "id": "walking_brisk",
        "name": "Brisk Walking",
        "category": "distance",
        "met": 4.3,
        "calories_per_km_per_kg": 0.70,
        "avg_speed_kmh": 5.0,
        "unit": "km",
    },
    "walking_hiking": {
        "id": "walking_hiking",
        "name": "Hiking / Trail Walking",
        "category": "distance",
        "met": 6.0,
        "calories_per_km_per_kg": 0.85,
        "avg_speed_kmh": 4.0,
        "unit": "km",
    },
    "rowing_machine": {
        "id": "rowing_machine",
        "name": "Rowing Machine",
        "category": "distance",
        "met": 7.0,
        "calories_per_km_per_kg": 0.50,
        "avg_speed_kmh": 8.0,
        "unit": "km",
    },
    "swimming_laps": {
        "id": "swimming_laps",
        "name": "Lap Swimming",
        "category": "distance",
        "met": 8.0,
        "calories_per_km_per_kg": 2.50,  # High water drag resistance factor
        "avg_speed_kmh": 2.5,
        "unit": "km",
    },

    # --- REP & SET-BASED EXERCISES ---
    "pushups": {
        "id": "pushups",
        "name": "Push-ups",
        "category": "reps",
        "met": 3.8,
        "cadence_sec_per_rep": 2.0,  # 2.0 seconds per rep standard tempo
        "default_sets": 3,
        "default_reps": 15,
    },
    "pullups": {
        "id": "pullups",
        "name": "Pull-ups / Chin-ups",
        "category": "reps",
        "met": 8.0,
        "cadence_sec_per_rep": 3.0,
        "default_sets": 3,
        "default_reps": 8,
    },
    "squats_bodyweight": {
        "id": "squats_bodyweight",
        "name": "Bodyweight Squats",
        "category": "reps",
        "met": 5.0,
        "cadence_sec_per_rep": 2.5,
        "default_sets": 3,
        "default_reps": 20,
    },
    "squats_barbell": {
        "id": "squats_barbell",
        "name": "Barbell Squats",
        "category": "reps",
        "met": 6.0,
        "cadence_sec_per_rep": 3.0,
        "default_sets": 4,
        "default_reps": 10,
    },
    "bench_press": {
        "id": "bench_press",
        "name": "Bench Press",
        "category": "reps",
        "met": 5.5,
        "cadence_sec_per_rep": 2.5,
        "default_sets": 4,
        "default_reps": 10,
    },
    "deadlift": {
        "id": "deadlift",
        "name": "Deadlift",
        "category": "reps",
        "met": 6.0,
        "cadence_sec_per_rep": 3.5,
        "default_sets": 4,
        "default_reps": 8,
    },
    "leg_press": {
        "id": "leg_press",
        "name": "Leg Press",
        "category": "reps",
        "met": 4.5,
        "cadence_sec_per_rep": 2.5,
        "default_sets": 4,
        "default_reps": 12,
    },
    "lunges": {
        "id": "lunges",
        "name": "Walking Lunges",
        "category": "reps",
        "met": 4.5,
        "cadence_sec_per_rep": 2.5,
        "default_sets": 3,
        "default_reps": 16,
    },
    "dips": {
        "id": "dips",
        "name": "Tricep Dips",
        "category": "reps",
        "met": 4.0,
        "cadence_sec_per_rep": 2.0,
        "default_sets": 3,
        "default_reps": 12,
    },
    "crunches": {
        "id": "crunches",
        "name": "Abdominal Crunches / Sit-ups",
        "category": "reps",
        "met": 3.5,
        "cadence_sec_per_rep": 2.0,
        "default_sets": 3,
        "default_reps": 25,
    },
    "leg_raises": {
        "id": "leg_raises",
        "name": "Hanging Leg Raises",
        "category": "reps",
        "met": 4.5,
        "cadence_sec_per_rep": 2.5,
        "default_sets": 3,
        "default_reps": 12,
    },
    "russian_twists": {
        "id": "russian_twists",
        "name": "Russian Twists",
        "category": "reps",
        "met": 4.0,
        "cadence_sec_per_rep": 1.5,
        "default_sets": 3,
        "default_reps": 20,
    },
    "mountain_climbers": {
        "id": "mountain_climbers",
        "name": "Mountain Climbers",
        "category": "reps",
        "met": 8.0,
        "cadence_sec_per_rep": 1.0,
        "default_sets": 3,
        "default_reps": 30,
    },
    "calf_raises": {
        "id": "calf_raises",
        "name": "Calf Raises",
        "category": "reps",
        "met": 3.5,
        "cadence_sec_per_rep": 2.0,
        "default_sets": 3,
        "default_reps": 20,
    },
    "burpees": {
        "id": "burpees",
        "name": "Burpees",
        "category": "reps",
        "met": 8.0,
        "cadence_sec_per_rep": 3.0,
        "default_sets": 3,
        "default_reps": 12,
    },
    "bicep_curls": {
        "id": "bicep_curls",
        "name": "Dumbbell Bicep Curls",
        "category": "reps",
        "met": 3.5,
        "cadence_sec_per_rep": 2.5,
        "default_sets": 3,
        "default_reps": 12,
    },
    "shoulder_press": {
        "id": "shoulder_press",
        "name": "Overhead Shoulder Press",
        "category": "reps",
        "met": 4.5,
        "cadence_sec_per_rep": 2.5,
        "default_sets": 3,
        "default_reps": 10,
    },

    # --- TIME & INTENSITY-BASED EXERCISES ---
    "football": {
        "id": "football",
        "name": "Football",
        "category": "time",
        "met_low": 5.0,
        "met_moderate": 7.0,
        "met_high": 9.0,
        "default_duration_min": 60.0,
    },
    "cricket": {
        "id": "cricket",
        "name": "Cricket",
        "category": "time",
        "met_low": 3.5,
        "met_moderate": 5.0,
        "met_high": 6.5,
        "default_duration_min": 90.0,
    },
    "padel": {
        "id": "padel",
        "name": "Padel",
        "category": "time",
        "met_low": 4.5,
        "met_moderate": 6.5,
        "met_high": 8.0,
        "default_duration_min": 60.0,
    },
    "yoga": {
        "id": "yoga",
        "name": "Yoga",
        "category": "time",
        "met_low": 2.5,
        "met_moderate": 3.3,
        "met_high": 4.0,
        "default_duration_min": 45.0,
    },
    "pilates": {
        "id": "pilates",
        "name": "Pilates",
        "category": "time",
        "met_low": 3.0,
        "met_moderate": 4.0,
        "met_high": 5.0,
        "default_duration_min": 45.0,
    },
    "jump_rope": {
        "id": "jump_rope",
        "name": "Jump Rope",
        "category": "time",
        "met_low": 8.8,
        "met_moderate": 11.0,
        "met_high": 12.3,
        "default_duration_min": 15.0,
    },
    "hiit_circuit": {
        "id": "hiit_circuit",
        "name": "HIIT / Circuit Training",
        "category": "time",
        "met_low": 6.0,
        "met_moderate": 8.0,
        "met_high": 10.0,
        "default_duration_min": 30.0,
    },
    "boxing": {
        "id": "boxing",
        "name": "Boxing / Kickboxing",
        "category": "time",
        "met_low": 5.5,
        "met_moderate": 7.8,
        "met_high": 10.0,
        "default_duration_min": 45.0,
    },
    "basketball": {
        "id": "basketball",
        "name": "Basketball",
        "category": "time",
        "met_low": 4.5,
        "met_moderate": 6.5,
        "met_high": 8.0,
        "default_duration_min": 60.0,
    },
    "tennis": {
        "id": "tennis",
        "name": "Tennis",
        "category": "time",
        "met_low": 4.0,
        "met_moderate": 5.0,
        "met_high": 7.3,
        "default_duration_min": 60.0,
    },
    "rock_climbing": {
        "id": "rock_climbing",
        "name": "Rock Climbing / Bouldering",
        "category": "time",
        "met_low": 5.0,
        "met_moderate": 7.5,
        "met_high": 9.0,
        "default_duration_min": 45.0,
    },
    "plank_hold": {
        "id": "plank_hold",
        "name": "Plank Isometric Hold",
        "category": "time",
        "met_low": 3.0,
        "met_moderate": 3.8,
        "met_high": 4.5,
        "default_duration_min": 3.0,
    },
}


def get_exercise_catalog_list() -> List[Dict[str, Any]]:
    """Returns list of catalog exercises sorted by category and name."""
    return list(EXERCISE_CATALOG.values())
